### ISSUE TITLE
add whoami & hostname (windows)

### ISSUE THREAD

**Issue by jinsanity07** [jinsanity07git/nodespecs#2]
```
(base) PS C:\Users\pe.AD> whoami
ad\pe
(base) PS C:\Users\ pe.AD > hostname
TC1
```

**Comment by jinsanity07git** [comment]
In Linux, the equivalents of the Windows Command Prompt commands hostname and whoami are the same—they are also called hostname and whoami.

**Comment by jinsanity07git** [comment]
the feature is added since `v.0.0.16`  9ad4f5b
